import { Brand, Product, StatusDefinition } from "@/types";

export const INITIAL_BRANDS: Brand[] = [
  {
    id: "elfliq",
    name: "Elfliq",
    description: "",
    image_url: "https://eliquid.shop.pl/cdn/shop/files/Myata_kolosistaya_elflik.png?v=1771953735&width=533",
  },
  {
    id: "vozol",
    name: "Vozol",
    description: "",
    image_url: "https://siomar.net/wp-content/uploads/2026/02/VOZOL-SaltNic-Prime-E-Liquids2.webp",
  },
  {
    id: "puffy",
    name: "Puffy",
    description: "",
    image_url: "https://pufflab.pro/wp-content/uploads/2026/01/Puffy-liquidy-30ml-Polska.webp",
  },
];

export const DEFAULT_STATUS_DEFINITIONS: StatusDefinition[] = [
  { id: "st-1", name: "Przyjęte", color: "blue", icon: "Package" },
  { id: "st-2", name: "Skompletowane", color: "purple", icon: "Boxes" },
  { id: "st-3", name: "W doręczeniu", color: "amber", icon: "Truck" },
  { id: "st-4", name: "Do odbioru", color: "cyan", icon: "ShoppingBag" },
  { id: "st-5", name: "Zrealizowane", color: "emerald", icon: "CheckCircle" },
  { id: "st-6", name: "Anulowane", color: "rose", icon: "AlertTriangle" },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "1",
    brand_id: "elfliq",
    name: "Watermelon",
    nicotine_strength: "50MG",
    volume_ml: "30ML",
    is_available: true,
    is_new: true,
    image_url: "",
  },
  {
    id: "2",
    brand_id: "elfliq",
    name: "Blueberry Sour Raspberry",
    nicotine_strength: "50MG",
    volume_ml: "30ML",
    is_available: true,
    is_new: false,
    image_url: "",
  },
  {
    id: "3",
    brand_id: "elfliq",
    name: "Apple Peach",
    nicotine_strength: "50MG",
    volume_ml: "30ML",
    is_available: false,
    is_new: false,
    image_url: "",
  },
  {
    id: "4",
    brand_id: "vozol",
    name: "Strawberry Kiwi",
    nicotine_strength: "50MG",
    volume_ml: "30ML",
    is_available: true,
    is_new: true,
    image_url: "",
  },
  {
    id: "5",
    brand_id: "vozol",
    name: "Cool Mint",
    nicotine_strength: "50MG",
    volume_ml: "30ML",
    is_available: true,
    is_new: false,
    image_url: "",
  },
  {
    id: "6",
    brand_id: "vozol",
    name: "Lush Ice",
    nicotine_strength: "50MG",
    volume_ml: "30ML",
    is_available: false,
    is_new: false,
    image_url: "",
  },
  {
    id: "7",
    brand_id: "puffy",
    name: "Grape Paradise",
    nicotine_strength: "50MG",
    volume_ml: "30ML",
    is_available: true,
    is_new: true,
    image_url: "",
  },
  {
    id: "8",
    brand_id: "puffy",
    name: "Mango Ice",
    nicotine_strength: "50MG",
    volume_ml: "30ML",
    is_available: true,
    is_new: false,
    image_url: "",
  },
];
